# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed6d7df2f31b4345dd0d57405a857a70775fdf8a034a8035648e0d8748efb2b76c5ed82d1fa295fa17a47a61d434a2f5e6042f61653439fa2c7945f405b549ff

test:
  secret_key_base: 1a01058f43f742dadf2260bee33b09d965a37f830b57764c47181e4d854085b1c1c7ced6c5218467cae04d0f8a2487f2f0fde6062f18391b3079b57c4cf714e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
